### ISSUE TITLE
Add `cache` to workflows using `actions/setup-node`

### ISSUE THREAD

**Issue by oscard0m** [semantic-release/error#167]
## New feature motivation
`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

## New feature description
- Add cache to workflows using actions/setup-node
- Remove other cache steps (if they exist) in the job.
   - ⚠️ Before removing (https://github.com/bahmutov/npm-install), check what it does and if it's safe to remove it or there should be extra work to do after adding native `setup-node` cache 

## New feature implementation
Something like this: https://github.com/semantic-release/error/pull/166 but considering existing cache steps.

**Comment by gr2m** [comment]
let's discuss in a single issue: https://github.com/semantic-release/semantic-release/issues/2010
